name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Dockerfile
        run: docker build -t "meatin:0.0.1" .
        
      - name: Run Docker
        run: docker-compose restart meatin
